console.log(0==false)
console.log(0===false)
console.log("---------------")
console.log(1=="1")
console.log(1==="1")
console.log("--------------")
console.log(null==undefined)
console.log(null===undefined)
